title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          text:
            label: Project Description
            type: textarea
            help: See our content styleguide
            required: true
          category:
            type: select
            options:
              - Analog
              - Digital
              - Screen Printing
              - Graphic Design
            width: 1/2
          year:
            before: Finished
            type: number
            min: 2015
            width: 1/2
          featured:
            type: toggle
            help: If featured, a project will appear on the homepage
            width: 1/2
          client:
            after: Universität
            type: text
            width: 1/2
            icon: user
            maxlength: 50
          link:
            label: Link To Project
            type: url
            width: 1/2
            icon: url
          tags:
            type: tags
            icon: tag
  - width: 1/2
    sections:
      gallery:
        headline: Project Gallery
        size: tiny
        info: "{{ file.alt }} {{ file.dimensions }}"
        type: files
        min: 1
        max: 10
        layout: cards
        # Now Every Uploaded Image gets the gallery-image template
        template: gallery-image
        image:
          ratio: 1/1
