title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          category:
            type: text
          text:
            type: textarea
          year:
            type: number
          client:
            type: text
  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        image:
          ratio: 1/1
